const getters = {
    sidebar: state => state.app.sidebar,
    device: state => state.app.device,
    token: state => state.user.token,
    userInfo: state => state.user.userInfo,
    dictMap: state => state.dict.dictMap,
    checkSts: state => state.dict.checkSts,
    sellSts: state => state.dict.sellSts,
    userRole: state => state.dict.userRole,
    orderType: state => state.dict.orderType,
    orderSts: state => state.dict.orderSts,
    afterSaleSts: state => state.dict.afterSaleSts,
    evaluateSts: state => state.dict.evaluateSts,
    payType: state => state.dict.payType,
    deliveryMode: state => state.dict.deliveryMode,
    refundType: state => state.dict.refundType,
    serviceType: state => state.dict.serviceType,
    answerSts: state => state.dict.answerSts,
    courseType: state => state.dict.courseType,
    queryType: state => state.dict.queryType,
    grabbingOrdersSts: state => state.dict.grabbingOrdersSts,
    makeOrderSts: state => state.dict.makeOrderSts,
    accessedRoutes: state => state.permission.accessedRoutes,
    permission_routes: state => state.permission.routes,
}
export default getters
