server:
  port: 10010
regist-center:
  ip: 127.0.0.1
  port: 18761
spring:
  application:
    name: gateway-local
  sleuth:
    baggage-keys:
      - Token
  main:
    allow-bean-definition-overriding: true
  mvc:
    favicon:
      enabled: false
  redis:
    host: 8.136.105.20
    port: 16379
    password: duling@2021!
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    #文件上传设置
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 2048MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 60000

eureka:
  instance:
    prefer-ip-address: false
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${regist-center.ip}:${regist-center.port}/eureka/
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Vary,X-Frame-Options,token
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
platform:
  enablePermissionVerify: false
  routerConfigProperties:
    privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBALrKi02NLBm3/WWOj1sSthKaQ+oINLVBt9SvwtdMwUjBtRTyc7/Js4PSnm9q4AXO5KPmGPrbw0Lr+RIJmHtSs/KSz6byw9P0LVLA6nvhXfpd8SGWnaQrOrRFLGpP4ioe2GpTiUnJ7m7Wn9+vf1qtMGb3wmS/BJxMB8YsReKhuYCPAgMBAAECgYBmg8LwTQpnExN/KT6EPUCv9PpQ9y/2SpsZn1zPzNBHnghD9syP9aMQNge+HmnUxje1vBL5mqMPl3Ka86k8Bae8CQ4GXssSstL2+N1jAlW73eSYg4HQD37lhpYzcSJ7OqA43DIkNPVik8Qq8q588OJe1+a6gcoFAHVNFrBDXsOcAQJBAOy5b08ob92HdzujpiAA009Gte5v8sGzRVOogObvM2/2VYp3kQtAGtszfpjDJNNcGO3cWJm774e4tfjqSVrd0EsCQQDKAD4nIIFBp2HQSrx55kaTcgE8fUTgT/BFXFMJlxbRTpVENT/BO17ZcHzwvw9dQCZzFUpDUNNpPwYYC7KtwU5NAkA0UEqD8Mi/6Rb1bBXjTqtkAplkBwNbwRVaBovt/QCeBo8i2YeJN/J3bKrWcZGqz9iGgEJoPvsRQEWeq4/ob8p/AkB5rxHB0jPrD+C9b/f/2rcTJS8XeELgeWc88TPYaBrHtXX3o7gnOBOYGso44G9p9jXzR5T33h2sndmW7J0TTIpVAkB4YpuZPtMEeH+FiJhojyfpQ6yDjMFFQR6vzyTGGGdebFNm7NdMcVqbbPc8UDIxVTwsOjUE0tDScmHyRBrCk3UR
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6yotNjSwZt/1ljo9bErYSmkPqCDS1QbfUr8LXTMFIwbUU8nO/ybOD0p5vauAFzuSj5hj628NC6/kSCZh7UrPyks+m8sPT9C1SwOp74V36XfEhlp2kKzq0RSxqT+IqHthqU4lJye5u1p/fr39arTBm98JkvwScTAfGLEXiobmAjwIDAQAB
    noFilterUrl:
      - /file/uploadFile
      - /file/uploadBase64Image
      - /login/userLogin
      - /oauth/userLogin
      - /login/getLoginCode
      - /oauth/token
      - /oauth/queryVerificationCode
      - /v2/api-docs
      - /swagger-resources
      - /swagger-resources/**
      - /configuration/**
      - /swagger-ui.html
      - /swagger-resources/configuration/ui
      - /doc.html
      - /dict/**
      - /webSocket
      - /statistics/**
      - /menu/queryMenuListByUser
      - /area/**
      - /technician/register
      - /storeTechnician/addStoreTechnicianRelate
      - /storeTechnician/queryStoreListByArea
      - /store/addStore
      - /pay/weChartBack
      - /vehicleConfig/queryAllList
      - /vehicleConfig/queryList
      - /vehicleConfig/queryConfig
      - /setting/getByCode
      - /setting/getById
      - /setting/list
      - /pay/aliPayBack
      - /contact/insert

